### ISSUE TITLE
Pre-filter Assembly Table, keeping only the assemblies present in the chosen pangenome .json file

### ISSUE THREAD

**Issue by SingingMeerkat** [CSSyngenta/savanache-vue3#3]
As of now, the Assembly Table component is kept between the first (1, scatterplot) and second (2, SVs) views. It should instead offer another Assembly Table (or the same but with filtered out elements), only containing the assemblies found in the pangenome.

The selection status from View 1 should be transferred to view 2.

**Comment by CSSyngenta** [comment]
If I understand this correctly, I did this earlier today.
